# DB Config
spring:
  datasource:
    url: jdbc:mysql://172.18.224.1:3306/void_db
    username: application
    password: Asisan#*2024
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Eureka Client Properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:5000/eureka

# Zipkin
management:
  tracing:
    sampling:
      probability: 1
